# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 594e15a0d2319dcd90be96a6408348575c5c949eaf3143048ba46a24fe025670ad614d4e20b8d580a4df5d7e881b2cdb7a5d33bc3c23aa4ec43c3f68b206a8ea

test:
  secret_key_base: e067021833debde3019f827c00149c3a294b515550bfcc51fbaf6da61f38489d8a7e23b90ff8e541132b4fc4156ff20ddcc13c50a5578872268ce8d48e628e82

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
