# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d13bf529e81c315d0542e36e3daa3c8249de4741752c986de8fc81cbd6d8121d55b633c617ce4288ff2ba04840dd3282e2757da4ec3ae54c0255ddca7ca0633

test:
  secret_key_base: 950a926b70b3dd2c9d3bfa50a81b51b92ef14881562fec1fee7bc04407090e02d96a222ce288b16c18473329fee9fe498b3631d70fdf02736984bc827612a59b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
