# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7cd92344ac966dd08776a856c08647c4e09a41c79e75f37643f27b7429d423b04894c303f934629eb2f81c90ecdddd52190d13efe247dd297c533cb68be1c185

test:
  secret_key_base: 8e12040ba21e57acf0fc95445e7cceedcde512404888588fe3074c59a8233ad089af52e758e63779a3bc0bcc0dd31229fd0a2c8d57c832ac22281e406fc8cc86

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
